name: My Actions
on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checking out
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v2
      with:
       python-version: 3.8
    - name: install libs
      run: |
        cd function
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
    - name: create zip
      run: |
        cd function
        zip -r ../${{ github.sha }}.zip .
    - name: archive
      uses: actions/upload-artifact@v2
      with:
        name: zipped-bundle
        path: ${{github.sha}}.zip
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: zipped-bundle
    - name: configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1
    - name: upload to s3
      run: aws s3 cp ${{github.sha}}.zip s3://aseef-452451244513/${{github.sha}}.zip
  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - name: configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: us-east-1
    - name: upload function
      run: |
        aws lambda update-function-code \
        --function-name myfunc \
        --s3-bucket aseef-452451244513 \
        --s3-key ${{github.sha}}.zip \
        --publish
    
    
    
    

        
